DROP TABLE REGION;
DROP TABLE SKILL_COLLECTION;
DROP TABLE EMPLOYEE;
DROP TABLE EMPLOYEE_SKILL;
DROP TABLE CUSTOMER;
DROP TABLE MANAGER;
DROP TABLE PROJECT;
DROP TABLE TASK;
DROP TABLE PROJECT_SCHEDULE;


CREATE TABLE REGION(
    REGION_ID VARCHAR2(8) PRIMARY KEY,
    REGION_NAME VARCHAR2(20) NOT NULL
);

CREATE TABLE SKILL_COLLECTION(
    SKILL_ID VARCHAR2(8) PRIMARY KEY,
    SKILL_DESCRIPTION VARCHAR2(25) NOT NULL,
    --No skill rate in the PDF, I don't know what to insert which is why it does not have NOT NULL constraint
    SKILL_RATE NUMBER(10)
);

CREATE TABLE EMPLOYEE(
    EMP_ID VARCHAR2(8) PRIMARY KEY,
    EMP_FNAME VARCHAR2(10) NOT NULL,
    EMP_MINITIAL VARCHAR2(10),
    EMP_LNAME VARCHAR2(10) NOT NULL,
    REGION_ID VARCHAR2(10) NOT NULL,
    DATE_OF_HIRE DATE NOT NULL,
    CONSTRAINT REGION_ID_EMPLOYEE_FK FOREIGN KEY (REGION_ID) REFERENCES REGION (REGION_ID)
    );

CREATE TABLE EMPLOYEE_SKILL(
    SKILL_ID VARCHAR2(8) NOT NULL,
    EMP_ID VARCHAR2(8) NOT NULL,
    CONSTRAINT EMPLOYEE_SKILL_PK PRIMARY KEY (SKILL_ID, EMP_ID),
    CONSTRAINT SKILL_ID_SKILL_FK FOREIGN KEY (SKILL_ID) REFERENCES SKILL_COLLECTION (SKILL_ID),
    CONSTRAINT EMP_ID_SKILL_FK FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

CREATE TABLE CUSTOMER(
    CUST_ID VARCHAR2(8) PRIMARY KEY,
    CUST_FNAME VARCHAR2(10) NOT NULL,
    CUST_LNAME VARCHAR2(10) NOT NULL,
    CUST_PHONE NUMBER(15) NOT NULL,
    REGION_ID VARCHAR2(10) NOT NULL,
    CONSTRAINT REGION_ID_CUSTOMER_FK FOREIGN KEY (REGION_ID) REFERENCES REGION (REGION_ID)
);

CREATE TABLE MANAGER(
    MANAGER_ID VARCHAR2(8) PRIMARY KEY,
    EMP_ID VARCHAR2(8) NOT NULL,
    CONSTRAINT EMP_ID_MANAGER_FK FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

CREATE TABLE PROJECT(
    PROJ_ID VARCHAR2(8) PRIMARY KEY,
    CUST_ID VARCHAR2(8) NOT NULL,
    MANAGER_ID VARCHAR2(8) NOT NULL,
    ASSIGN_ID VARCHAR2(8) NOT NULL,
    PRJ_DESCRIPTION VARCHAR2(20),
    PRJ_CONTRACT_DATE DATE NOT NULL,
    EST_PRJ_START_DATE DATE NOT NULL,
    EST_PRJ_END_DATE DATE NOT NULL,
    EST_PROJECT_BUDGET NUMBER(15,2) NOT NULL,
    --RECORDS PROJECT WITHOUT FINAL DATE THAT IS WHY THERE IS NOT NOT NULL FOR ACTUAL DATES BELOW
    --The actual cost of the project is updated each Friday by adding that week’s cost to the actual cost.
    --The week’s cost is computed by multiplying the hours each employee worked by the rate of pay for that skill.
    ACTUAL_START_DATE DATE,
    ACTUAL_END_DATE DATE,
    ACTUAL_COST NUMBER(15,2) NOT NULL,
    CONSTRAINT CUST_ID_PROJECT_FK FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (CUST_ID),
    CONSTRAINT MANAGER_ID_PROJECT_FK FOREIGN KEY (MANAGER_ID) REFERENCES MANAGER (MANAGER_ID)
    --CHECK FOR REGION BUT HOW
);

CREATE TABLE TASK(
    TASK_ID VARCHAR2(8) PRIMARY KEY,
    TASK_DESCRIPTION VARCHAR2(20) NOT NULL,
    TASK_START_DATE DATE NOT NULL,
    TASK_END_DATE DATE NOT NULL,
    SKILL_ID VARCHAR2(8) NOT NULL,
    --WE CAN USE A GROUP BY TO COUNT AND CHECK THE QUANTITY?
    QTY_NEEDED NUMBER(5) NOT NULL
);

CREATE TABLE PROJECT_SCHEDULE(
    SCHEDULE_ID VARCHAR2(8) PRIMARY KEY,
    PROJ_ID VARCHAR2(8) NOT NULL,
    MANAGER_ID VARCHAR2(8) NOT NULL,
    REGION_ID VARCHAR2(8) NOT NULL,
    TASK_ID VARCHAR2(8) NOT NULL,
    CONSTRAINT PRJ_ID_PROJECT_SCHEDULE_FK FOREIGN KEY (PROJ_ID) REFERENCES PROJECT (PROJ_ID),
    CONSTRAINT MANAGER_ID_PROJECT_SCHEDULE_FK FOREIGN KEY (MANAGER_ID) REFERENCES MANAGER (MANAGER_ID),
    CONSTRAINT REGION_ID_PROJECT_SCHEDULE_FK FOREIGN KEY (REGION_ID) REFERENCES REGION (REGION_ID),
    CONSTRAINT TASK_ID_PROJECT_SCHEDULE_FK FOREIGN KEY (TASK_ID) REFERENCES TASK (TASK_ID)
);


