INSERT INTO REGION VALUES ('REGION_1', 'Northwest (NW)');
INSERT INTO REGION VALUES ('REGION_2', 'Southwest (SW)');
INSERT INTO REGION VALUES ('REGION_3', 'Midwest North (MN)');
INSERT INTO REGION VALUES ('REGION_4', 'Midwest South (MS)');
INSERT INTO REGION VALUES ('REGION_5', 'Northeast (NE)');
INSERT INTO REGION VALUES ('REGION_6', 'Southeast (SE)');

INSERT INTO SKILL_COLLECTION VALUES ('SKILL_1', 'Data Entry I', NULL);
INSERT INTO SKILL_COLLECTION VALUES ('SKILL_2', 'Data Entry II', NULL);
INSERT INTO SKILL_COLLECTION VALUES ('SKILL_3', 'Systems Analyst I', NULL);
INSERT INTO SKILL_COLLECTION VALUES ('SKILL_4', 'Systems Analyst II', NULL);
INSERT INTO SKILL_COLLECTION VALUES ('SKILL_5', 'Database Designer I', NULL);
INSERT INTO SKILL_COLLECTION VALUES ('SKILL_6', 'Database Designer II', NULL);
INSERT INTO SKILL_COLLECTION VALUES ('SKILL_7', 'Java I', NULL);
INSERT INTO SKILL_COLLECTION VALUES ('SKILL_8', 'Java II', NULL);
INSERT INTO SKILL_COLLECTION VALUES ('SKILL_9', 'C++ I', NULL);
INSERT INTO SKILL_COLLECTION VALUES ('SKILL_10', 'C++ II', NULL);
INSERT INTO SKILL_COLLECTION VALUES ('SKILL_11', 'Python I', NULL);
INSERT INTO SKILL_COLLECTION VALUES ('SKILL_12', 'Python II', NULL);
INSERT INTO SKILL_COLLECTION VALUES ('SKILL_13', 'ColdFusion I', NULL);
INSERT INTO SKILL_COLLECTION VALUES ('SKILL_14', 'ColdFusion II', NULL);
INSERT INTO SKILL_COLLECTION VALUES ('SKILL_15', 'ASP I', NULL);
INSERT INTO SKILL_COLLECTION VALUES ('SKILL_16', 'ASP II', NULL);
INSERT INTO SKILL_COLLECTION VALUES ('SKILL_17', 'Oracle DBA', NULL);
INSERT INTO SKILL_COLLECTION VALUES ('SKILL_18', 'MS SQL Server DBA', NULL);
INSERT INTO SKILL_COLLECTION VALUES ('SKILL_19', 'Network Engineer I', NULL);
INSERT INTO SKILL_COLLECTION VALUES ('SKILL_20', 'Network Engineer II', NULL);
INSERT INTO SKILL_COLLECTION VALUES ('SKILL_21', 'Web Administrator', NULL);
INSERT INTO SKILL_COLLECTION VALUES ('SKILL_22', 'Technical Writer', NULL);
INSERT INTO SKILL_COLLECTION VALUES ('SKILL_23', 'Project Manager', NULL);



SELECT * FROM REGION;
SELECT * FROM SKILL_COLLECTION;
SELECT * FROM EMPLOYEE;
SELECT * FROM EMPLOYEE_SKILL;
SELECT * FROM CUSTOMER;
SELECT * FROM MANAGER;
SELECT * FROM PROJECT;
SELECT * FROM TASK;
SELECT * FROM PROJECT_SCHEDULE;