CREATE OR REPLACE VIEW Project_View AS
SELECT PROJECT.PROJ_ID, PROJECT.CUST_ID, PROJECT.MANAGER_ID, PROJECT.PRJ_DESCRIPTION, 
PROJECT.PRJ_CONTRACT_DATE, PROJECT.EST_PRJ_START_DATE, PROJECT.EST_PRJ_END_DATE, 
PROJECT.EST_PROJECT_BUDGET, PROJECT.ACTUAL_START_DATE, PROJECT.ACTUAL_END_DATE, 
PROJECT.ACTUAL_COST NUMBER, CUSTOMER.CUST_FNAME, CUSTOMER.CUST_LNAME, MANAGER.MANAGER_ID, ASSIGNMENT.ASSIGNMENT_ID
FROM PROJECT
JOIN CUSTOMER_ID ON PROJECT.CUST_ID=CUSTOMER.CUST_ID
JOIN MANAGER_ID ON PROJECT.MANAGER_ID=MANAGER.MANAGER_ID
JOIN ASSIGNMENT_ID ON PROJECT.ASSIGNMENT_ID=ASSIGNMENT.ASSIGNMENT_ID

ORDER BY LENGTH (PROJ_ID), PROJ_ID ASC;
SELECT * FROM Project_View;