CREATE PROCEDURE SHOW_DATA
AS
BEGIN
    SELECT * FROM REGION;
    SELECT * FROM SKILL_COLLECTION;
    SELECT * FROM EMPLOYEE;
    SELECT * FROM EMPLOYEE_SKILL;
    SELECT * FROM CUSTOMER;
    SELECT * FROM MANAGER;
    SELECT * FROM PROJECT;
    SELECT * FROM TASK;
    SELECT * FROM PROJECT_SCHEDULE;
    SELECT * FROM ASSIGNMENT;
    SELECT * FROM BILL;
    SELECT * FROM WORK_LOG;
END;